apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  database: telegraf
  user: telegraf
  password: secretpassword
  url: http://influxdb:8086
  isDefault: true
  editable: true
  jsonData:
    timeInterval: "10s"
